### ISSUE TITLE
Personalize Profile

### ISSUE THREAD

**Issue by dbukauskas** [SIU-CS-435/Alpha-Learning#11]
As a user I would like to be able to edit my profile so that other users can learn more about me

**Comment by AndrewKralovec** [comment]
Yup, i created a profile feature and is was mostly completed. The user could see his courses,posts, his ranking. However, seeing as there were a lot of features we wanted, but never got finished, not everything on the profile page is functional.However, if they features get finished, I have the page set up to be able to implement them.
