### ISSUE TITLE
Create quiz

### ISSUE THREAD

**Issue by AndrewKralovec** [SIU-CS-435/Alpha-Learning#36]
We need to get the create a quiz options up there, we dont have a lot of time and there is still a bunch of things that i need to be done

**Comment by TylerNethery1994** [comment]
added a pull request the files are not merged with main branch . 
also $routeProvider was giving me issues would not load home.html

**Comment by AndrewKralovec** [comment]
Took care of it, need to just implement the inserting into database. Which has to wait for the routes reassigning.
